alias ls='ls -G'
alias ll='ls -alh'
alias grep='grep --color'
alias tree='tree -N'
alias de='cd ~/Desktop'
alias code='open -b com.microsoft.VSCode'
alias atom='open -b com.github.atom'
alias iconv-gb18030='iconv -f gb18030'
alias cwd='pwd | pbcopy'
alias ls-npm='npm -g ls --depth 0'
alias py-serve='python3 -m http.server'

alias de='cd ~/Desktop'
alias gg='cd ~/Developer/GitHub'
alias ss='export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890'
